/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beanmanager.ajustes;

import beanmanager.controles.*;
import java.awt.Color;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author jacky
 */
public class AgregarPermiso extends javax.swing.JFrame {
    List<String> idRol,idModulo;
    /**
     * Creates new form AgregarPermiso
     */
    public AgregarPermiso() {
        initComponents();
        setTitle("Bean Manager");
        setLocationRelativeTo(null);
        setLayout(null);
        setResizable(false);
        this.getContentPane().setBackground(Color.decode("#FFFFFF"));
        CargarRoles();
        CargarModulos();
    }
     public void CargarRoles(){
        try{
            Bdd conexion = new Bdd();
            String consulta="SELECT * FROM `rolesProyecto` WHERE `eliminado`=0";
            Statement stmt = conexion.con.createStatement();
            ResultSet resultado = stmt.executeQuery(consulta);
            idRol= new ArrayList<String>();
            while(resultado.next())
            {
                idRol.add(resultado.getString("idRol"));
                jcmbRol.addItem(resultado.getString("rol"));
            }
            conexion.close();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
     public void CargarModulos(){
        try{
            Bdd conexion = new Bdd();
            String consulta="SELECT * FROM `Modulos` WHERE `eliminado`=0";
            Statement stmt = conexion.con.createStatement();
            ResultSet resultado = stmt.executeQuery(consulta);
            idModulo= new ArrayList<String>();
            while(resultado.next())
            {
                idModulo.add(resultado.getString("idModulo"));
                jcmbModulo.addItem(resultado.getString("modulo"));
            }
            conexion.close();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
     public void Agregar()
     {
         try
        {
                Bdd conexion = new Bdd();
                String consulta="INSERT INTO `PermisosRoles`(`idRol`, `idModulo`, `modificar`, "
                        + "`agregar`, `borrar`, `ingresar`, `eliminado`) VALUES ("+idRol.get(jcmbRol.getSelectedIndex())+","+idModulo.get(jcmbModulo.getSelectedIndex())
                        +","+jcbModificar.isSelected()+","+jcbAgregar.isSelected()+","+jcbBorrar.isSelected()+","+jcbIngresar.isSelected()+",0)";
                Statement stmt = conexion.con.createStatement();
                int agregado = stmt.executeUpdate(consulta);
                if(agregado>0)
                {
                    JOptionPane.showMessageDialog(null, "Se han agregado los permisos con éxito.");
                    conexion.close();
                    permisos jfmPermisos = new permisos();
                    jfmPermisos.setVisible(true);
                    this.setVisible(false);
                }
                else
                {
                    conexion.close();
                    JOptionPane.showMessageDialog(null, "No se pudo agregar los permisos.");
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcmbRol = new javax.swing.JComboBox<>();
        jcmbModulo = new javax.swing.JComboBox<>();
        jcbIngresar = new javax.swing.JCheckBox();
        jcbAgregar = new javax.swing.JCheckBox();
        jcbModificar = new javax.swing.JCheckBox();
        jcbBorrar = new javax.swing.JCheckBox();
        jbnCancelar = new javax.swing.JButton();
        jbnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Agregar permiso");

        jLabel2.setText("Rol:");

        jLabel3.setText("Módulo: ");

        jcbIngresar.setText("Ingresar");

        jcbAgregar.setText("Agregar");

        jcbModificar.setText("Modificar");

        jcbBorrar.setText("Borrar");

        jbnCancelar.setText("Cancelar");
        jbnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnCancelarActionPerformed(evt);
            }
        });

        jbnAgregar.setText("Agregar");
        jbnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAgregarActionPerformed(evt);
            }
        });

        jLabel4.setText("Permisos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbIngresar)
                            .addComponent(jcbModificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbBorrar)
                            .addComponent(jcbAgregar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcmbRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcmbModulo, 0, 151, Short.MAX_VALUE)))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcmbModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbIngresar)
                    .addComponent(jcbAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbModificar)
                    .addComponent(jcbBorrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnCancelar)
                    .addComponent(jbnAgregar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAgregarActionPerformed
        // TODO add your handling code here:
        Agregar();
    }//GEN-LAST:event_jbnAgregarActionPerformed

    private void jbnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnCancelarActionPerformed
        // TODO add your handling code here:
        permisos jfmPermisos = new permisos();
        jfmPermisos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPermiso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbnAgregar;
    private javax.swing.JButton jbnCancelar;
    private javax.swing.JCheckBox jcbAgregar;
    private javax.swing.JCheckBox jcbBorrar;
    private javax.swing.JCheckBox jcbIngresar;
    private javax.swing.JCheckBox jcbModificar;
    private javax.swing.JComboBox<String> jcmbModulo;
    private javax.swing.JComboBox<String> jcmbRol;
    // End of variables declaration//GEN-END:variables
}
