/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beanmanager.ajustes;

import beanmanager.controles.*;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author jacky
 */
public class ModificarPermisoTipo extends javax.swing.JFrame {
    String idPermiso;
    /**
     * Creates new form ModificarPermiso
     */
    public ModificarPermisoTipo(String id) {
        idPermiso= id;
        initComponents();
        setLocationRelativeTo(null);
        setLayout(null);
        this.getContentPane().setBackground(Color.decode("#FFFFFF"));
        CargarDatos();
        
    }
    public void CargarDatos()
    {
        try{
            Boolean permiso;
            Bdd conexion = new Bdd();
            String consulta="SELECT `idPermiso`, `TiposUsuario`.`tipo` as 'tipo', `Modulos`.`modulo` as 'modulo', `modificar`, "
                    + "`agregar`, `borrar`, `ingresar` FROM `Permisos` inner join `TiposUsuario` on "
                    + "`TiposUsuario`.`idTipo`= `Permisos`.`idTipo` inner join `Modulos` on `Modulos`.`idModulo` = `Permisos`.`idModulo` "
                    + "WHERE `idPermiso`="+idPermiso;
            Statement stmt = conexion.con.createStatement();
            ResultSet resultado = stmt.executeQuery(consulta);
            if(resultado.next())
            {
                jlbTipo.setText(resultado.getString("tipo"));
                jlbModulo.setText("Módulo: "+resultado.getString("modulo"));
                permiso = (resultado.getBoolean("ingresar"));
                jcbIngresar.setSelected(permiso);
                permiso = (resultado.getBoolean("agregar"));
                jcbAgregar.setSelected(permiso);
                permiso = (resultado.getBoolean("modificar"));
                jdbModificar.setSelected(permiso);
                permiso = (resultado.getBoolean("borrar"));
                jcbBorrar.setSelected(permiso);
              }
            conexion.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
    }
    public void Modificar()
    {
        try
        {
                Bdd conexion = new Bdd();
                String consulta="UPDATE `PermisosRoles` SET `modificar`="+jdbModificar.isSelected()+", `agregar`="+jcbAgregar.isSelected()+",`borrar`="+jcbBorrar.isSelected()+","
                        + "`ingresar`="+jcbIngresar.isSelected()+" WHERE `idPermiso`="+idPermiso;
                Statement stmt = conexion.con.createStatement();
                int agregado = stmt.executeUpdate(consulta);
                if(agregado>0)
                {
                    JOptionPane.showMessageDialog(null, "Se han modificado los permisos con éxito.");
                    conexion.close();
                    permisos jfmPermisos = new permisos();
                    jfmPermisos.setVisible(true);
                    this.setVisible(false);
                }
                else
                {
                    conexion.close();
                    JOptionPane.showMessageDialog(null, "No se pudo modificar los permisos.");
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbnCancelar = new javax.swing.JButton();
        jlbTipo = new javax.swing.JLabel();
        jlbModulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbIngresar = new javax.swing.JCheckBox();
        jcbAgregar = new javax.swing.JCheckBox();
        jdbModificar = new javax.swing.JCheckBox();
        jcbBorrar = new javax.swing.JCheckBox();
        jbnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modificar Permisos");

        jbnCancelar.setText("Cancelar");
        jbnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnCancelarActionPerformed(evt);
            }
        });

        jlbTipo.setText("prueba");

        jlbModulo.setText("Prueba");

        jLabel2.setText("Permisos:");

        jcbIngresar.setText("Ingresar");

        jcbAgregar.setText("Agregar");

        jdbModificar.setText("Modificar");

        jcbBorrar.setText("Borrar");

        jbnModificar.setText("Modificar");
        jbnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbIngresar)
                            .addComponent(jdbModificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbBorrar)
                            .addComponent(jcbAgregar))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbModulo)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jlbTipo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addComponent(jbnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jbnCancelar)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlbTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbModulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbIngresar)
                    .addComponent(jcbAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdbModificar)
                    .addComponent(jcbBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnCancelar)
                    .addComponent(jbnModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnCancelarActionPerformed
        // TODO add your handling code here:
        PermisosTipo jfmPermisos = new PermisosTipo();
        jfmPermisos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbnCancelarActionPerformed

    private void jbnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnModificarActionPerformed
        // TODO add your handling code here:
         Modificar();
    }//GEN-LAST:event_jbnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPermisoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPermisoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPermisoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPermisoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPermisoTipo("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbnCancelar;
    private javax.swing.JButton jbnModificar;
    private javax.swing.JCheckBox jcbAgregar;
    private javax.swing.JCheckBox jcbBorrar;
    private javax.swing.JCheckBox jcbIngresar;
    private javax.swing.JCheckBox jdbModificar;
    private javax.swing.JLabel jlbModulo;
    private javax.swing.JLabel jlbTipo;
    // End of variables declaration//GEN-END:variables
}
