/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beanmanager.ajustes;
import beanmanager.clases.Usuario;
import beanmanager.controles.*;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jacky
 */
public class ModificarRol extends javax.swing.JFrame {
    String idRol;
    Usuario session;
    /**
     * Creates new form ModificarRol
     */
    public ModificarRol(String id, Usuario u) {
        idRol = id;
        initComponents();
        setResizable(false);
        setTitle("Bean Manager");
        setLocationRelativeTo(null);
        setLayout(null);
        this.getContentPane().setBackground(Color.decode("#FFFFFF"));
        CargarDatos();
        session = u;
    }
    public void CargarDatos()
    {
        try{
            Bdd conexion = new Bdd();
            String consulta="SELECT * FROM `rolesProyecto` WHERE `eliminado`=0 and `idRol`="+idRol;
            Statement stmt = conexion.con.createStatement();
            ResultSet resultado = stmt.executeQuery(consulta);
            while(resultado.next())
            {
                this.jtfNombre.setText(resultado.getString("rol"));
                this.jtaDescripcion.setText(resultado.getString("descripcion"));
            }
            conexion.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
    }
    public void Modificar(String Rol, String des)
    {
        try
        {
            if(this.jtfNombre.getText().equals("") || this.jtaDescripcion.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Es necesario que llene todos los campos");
            }
            else
            {
                Bdd conexion = new Bdd();
                String consulta="UPDATE `rolesProyecto` SET `rol`='"+Rol+"',`descripcion`='"+des+"' WHERE `idRol`="+idRol;
                Statement stmt = conexion.con.createStatement();
                int agregado = stmt.executeUpdate(consulta);
                if(agregado>0)
                {
                    JOptionPane.showMessageDialog(null, "Se ha modificado el rol con éxito.");
                    conexion.close();
                    Roles jfmRoles = new Roles(session);
                    jfmRoles.setVisible(true);
                    this.setVisible(false);
                }
                else
                {
                    conexion.close();
                    JOptionPane.showMessageDialog(null, "No se pudo modificar el rol.");
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
    }
    public void Eliminar()
    {
        try
        {
            if(this.jtfNombre.getText().equals("") || this.jtaDescripcion.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Es necesario que llene todos los campos");
            }
            else
            {
                Bdd conexion = new Bdd();
                String consulta="UPDATE `rolesProyecto` SET `eliminado`=1 WHERE `idRol`="+idRol;
                Statement stmt = conexion.con.createStatement();
                int agregado = stmt.executeUpdate(consulta);
                if(agregado>0)
                {
                    JOptionPane.showMessageDialog(null, "Se ha eliminado el rol con éxito.");
                    conexion.close();
                    Roles jfmRoles = new Roles(session);
                    jfmRoles.setVisible(true);
                    this.setVisible(false);
                }
                else
                {
                    conexion.close();
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el rol.");
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescripcion = new javax.swing.JTextArea();
        jbnModificar = new javax.swing.JButton();
        jbnCancelar = new javax.swing.JButton();
        jbnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Modificar/Eliminar Rol");

        jLabel2.setText("Nombre Rol:");

        jLabel3.setText("Descripción:");

        jtaDescripcion.setColumns(20);
        jtaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jtaDescripcion);

        jbnModificar.setText("Modifcar");
        jbnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnModificarActionPerformed(evt);
            }
        });

        jbnCancelar.setText("Cancelar");
        jbnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnCancelarActionPerformed(evt);
            }
        });

        jbnEliminar.setText("Eliminar rol");
        jbnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbnModificar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbnCancelar)
                        .addComponent(jbnEliminar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnModificarActionPerformed
        // TODO add your handling code here:
        String nombre = this.jtfNombre.getText(),
               descripcion = this.jtaDescripcion.getText();
        Modificar(nombre,descripcion);
    }//GEN-LAST:event_jbnModificarActionPerformed

    private void jbnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnCancelarActionPerformed
        // TODO add your handling code here:
        Roles jfmRoles = new Roles(session);
        jfmRoles.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbnCancelarActionPerformed

    private void jbnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnEliminarActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea realizar el cierre de notas?");
        if(opc==0)
        {
            Eliminar();
        }
    }//GEN-LAST:event_jbnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarRol("",null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnCancelar;
    private javax.swing.JButton jbnEliminar;
    private javax.swing.JButton jbnModificar;
    private javax.swing.JTextArea jtaDescripcion;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
