/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beanmanager.ajustes;
import beanmanager.controles.*;
import beanmanager.clases.*;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.DefaultCellEditor;
import javax.swing.table.*;
import javax.swing.JCheckBox;

/**
 
 * @author jacky
 */
public class permisos extends javax.swing.JFrame {
    public Permiso permiso;
    Usuario session;
    DefaultTableModel ModelPermisos;
    List<String> idRol;
    String[] columnas = new String[]{"id","Modulo","Ingresar","Agregar","Modificar","Borrar"};
    /**
     * Creates new form permisos
     */
    public permisos(Usuario u) {
        ModelPermisos = new DefaultTableModel(null,columnas) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
              @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }
            @Override
            public boolean isCellEditable (int fila, int columna) {
                return false;
            }
        };
        initComponents();
        setLocationRelativeTo(null);
        CargarRoles();
        setLayout(null);
        this.getContentPane().setBackground(Color.decode("#FFFFFF"));
        this.jtbPermisos.getColumnModel().getColumn(0).setMaxWidth(0);
        this.jtbPermisos.getColumnModel().getColumn(0).setMinWidth(0);
        this.jtbPermisos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        this.jtbPermisos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        session = u;
        permiso = session.getPermiso("4");
        if(!permiso.agregar){this.jbnAgregar.setVisible(false);}

    }

    public void CargarPermisos(){
       try{
            int rows = ModelPermisos.getRowCount();
            for(int j = 0; j<rows;j++)
            {
                ModelPermisos.removeRow(0);
            }
            Bdd conexion = new Bdd();
            String consulta="SELECT `idPermiso`, `Modulos`.`modulo` as 'modulo',`ingresar`,`agregar`,`modificar`,`borrar`"
                    + "FROM `PermisosRoles` inner join `Modulos` on `Modulos`.`idModulo` = `PermisosRoles`.`idModulo` "
                    + "WHERE `PermisosRoles`.`eliminado`=0 and `idRol`="+idRol.get(jcmbRol.getSelectedIndex());
            Statement stmt = conexion.con.createStatement();
            ResultSet resultado = stmt.executeQuery(consulta);
            Object[] datos = new Object[6];
            while(resultado.next())
            {
                datos[0]=resultado.getObject(1);
                datos[1]=resultado.getObject(2);
                for(int i=2;i<6;i++)
                {
                      datos[i] = (resultado.getObject(i+1).toString().equals("1"))?true:false;
                }
               this.ModelPermisos.addRow(datos);
            }
            conexion.close();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void CargarRoles(){
        try{
            Bdd conexion = new Bdd();
            String consulta="SELECT * FROM `rolesProyecto` WHERE `eliminado`=0";
            Statement stmt = conexion.con.createStatement();
            ResultSet resultado = stmt.executeQuery(consulta);
            idRol= new ArrayList<String>();
            while(resultado.next())
            {
                idRol.add(resultado.getString("idRol"));
                jcmbRol.addItem(resultado.getString("rol"));
            }
            conexion.close();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbTitulo = new javax.swing.JLabel();
        jlbRol = new javax.swing.JLabel();
        jcmbRol = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPermisos = new javax.swing.JTable();
        jbnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlbHome = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));

        jlbTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitulo.setText("Permisos de roles ");
        jlbTitulo.setAutoscrolls(true);

        jlbRol.setText("Rol de usuario");

        jcmbRol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbRolItemStateChanged(evt);
            }
        });

        jtbPermisos.setModel(ModelPermisos);
        jtbPermisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbPermisosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbPermisos);

        jbnAgregar.setText("Agregar permiso");
        jbnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Para modificar los permisos del rol, de click en la fila del modulo que desea cambiar.");

        jlbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beanmanager/recursos/imagenes/home.png"))); // NOI18N
        jlbHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbHome))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jlbRol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbHome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbRol)
                    .addComponent(jcmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbRolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbRolItemStateChanged
        // TODO add your handling code here:
        CargarPermisos();
    }//GEN-LAST:event_jcmbRolItemStateChanged

    private void jtbPermisosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbPermisosMouseClicked
        // TODO add your handling code here:
         if(permiso.modificar){
             int i= this.jtbPermisos.getSelectedRow();
            String idPermiso = this.jtbPermisos.getValueAt(i, 0).toString();

            ModificarPermisos jfmModificar = new ModificarPermisos(idPermiso,session);
            jfmModificar.setVisible(true);
            this.setVisible(false);
         }
         else
         {
             JOptionPane.showMessageDialog(null, "No tienes permiso para modificar");        
         }
        
    }//GEN-LAST:event_jtbPermisosMouseClicked

    private void jbnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAgregarActionPerformed
        // TODO add your handling code here:
        AgregarPermiso jfmAgregar = new AgregarPermiso(session);
        jfmAgregar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbnAgregarActionPerformed

    private void jlbHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHomeMouseClicked
        // TODO add your handling code here:
        InicioAjustes jfmAjustes = new InicioAjustes(session);
        jfmAjustes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlbHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new permisos(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnAgregar;
    private javax.swing.JComboBox<String> jcmbRol;
    private javax.swing.JLabel jlbHome;
    private javax.swing.JLabel jlbRol;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JTable jtbPermisos;
    // End of variables declaration//GEN-END:variables
}
