/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beanmanager.ajustes;
import beanmanager.clases.*;
import beanmanager.controles.*;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.table.*;

/**
 *
 * @author jacky
 */
public class Roles extends javax.swing.JFrame {
    public Permiso permiso;
     public Usuario session;
    DefaultTableModel ModeloJtbRoles;
    String[] columnas = new String[]{"id","Rol","Descripción"};
    /**
     * Creates new form Roles
     */
    public Roles(Usuario u) {
        ModeloJtbRoles = new DefaultTableModel(null,columnas) {
            @Override
            public boolean isCellEditable (int fila, int columna) {
                return false;
            }
        };
        CargarRoles();
        initComponents();
        this.jtbRoles.setAutoscrolls(true);
        setTitle("Bean Manager");
        setResizable(false);
        setLocationRelativeTo(null);
        setLayout(null);
        this.getContentPane().setBackground(Color.decode("#FFFFFF"));
        this.jtbRoles.getColumnModel().getColumn(0).setMaxWidth(0);
        this.jtbRoles.getColumnModel().getColumn(0).setMinWidth(0);
        this.jtbRoles.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        this.jtbRoles.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        session=u;
        permiso = session.getPermiso("4");
         if(!permiso.agregar){this.jbnAgregar.setVisible(false);}
         
    }
    public void CargarRoles(){
        try{
            Bdd conexion = new Bdd();
            String consulta="SELECT * FROM `rolesProyecto` WHERE `eliminado`=0";
            Statement stmt = conexion.con.createStatement();
            ResultSet resultado = stmt.executeQuery(consulta);
            Object[] datos = new Object[3];
            while(resultado.next())
            {
                datos[0] = resultado.getObject(1);
                datos[1] = resultado.getObject(2);
                datos[2] = resultado.getObject(3);
                this.ModeloJtbRoles.addRow(datos);
            }
            conexion.close();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbRoles = new javax.swing.JTable();
        jbnAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlbHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Roles de proyecto");

        jtbRoles.setModel(ModeloJtbRoles);
        jtbRoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbRolesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbRoles);

        jbnAgregar.setText("Agregar Rol");
        jbnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Para modificar o eliminar un rol, de click en la fila.");

        jlbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beanmanager/recursos/imagenes/home.png"))); // NOI18N
        jlbHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbnAgregar)
                                .addGap(14, 14, 14))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlbHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAgregarActionPerformed
        // TODO add your handling code here:
        AgregarRol jfmAgregar = new AgregarRol(session);
        jfmAgregar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbnAgregarActionPerformed

    private void jtbRolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbRolesMouseClicked
        // TODO add your handling code here:
        if(permiso.modificar){
            int i= this.jtbRoles.getSelectedRow();
            String idRol = this.jtbRoles.getValueAt(i, 0).toString();
            ModificarRol jfmModificar = new ModificarRol(idRol,session);
            jfmModificar.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No tienes permiso para modificar");
        }
    }//GEN-LAST:event_jtbRolesMouseClicked

    private void jlbHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHomeMouseClicked
        // TODO add your handling code here:
        InicioAjustes jfmAjustes = new InicioAjustes(session);
        jfmAjustes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlbHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Roles(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnAgregar;
    private javax.swing.JLabel jlbHome;
    private javax.swing.JTable jtbRoles;
    // End of variables declaration//GEN-END:variables
}
