/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beanmanager.solicitudes;

import beanmanager.clases.Proyecto;
import beanmanager.clases.Usuario;
import beanmanager.controles.Bdd;
import beanmanager.proyectos.IndexProyecto;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class Detalles extends javax.swing.JInternalFrame {
     VerRequerimientos req;
     public IndexSolicitud padre;
     public Proyecto actual;
     Bdd db;
    public Usuario session;
    
    /**
     * Creates new form Detalles
     */
    public Detalles() {
        initComponents();
    }
    
    public  Detalles(IndexSolicitud p)
    {
        initComponents();
        req= new VerRequerimientos(p);
        padre = p;
        db = padre.db;
        getContentPane().setBackground(Color.white);
        jPanel1.setBackground(Color.white);
        jPanel2.setBackground(Color.white);
        jPanel3.setBackground(Color.white);
        jPanel4.setBackground(Color.white);
        jPanel5.setBackground(Color.white);
        jPanel6.setBackground(Color.white);
        jPanel7.setBackground(Color.white);
        jPanel8.setBackground(Color.white);
        txtDes.setEditable(false);
    }

    public void setActual()
    {
        lblTitulo.setText(actual.titulo);
        lblFecha.setText(actual.fechaCreacion);
        lblFI.setText(actual.fechaInicio);
        lblFF.setText(actual.fechaFinal);
        lblPedido.setText(actual.idUsuario);
        txtDes.setText(actual.descripcion);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFI = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblFF = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblPedido = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtDes = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btnReq = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBorder(null);
        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        jLabel5.setText("Titulo:");
        jPanel3.add(jLabel5);

        lblTitulo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblTitulo.setText("Titulo proyecto");
        jPanel3.add(lblTitulo);

        jPanel2.add(jPanel3);

        jLabel11.setText("Fecha:");
        jPanel6.add(jLabel11);

        lblFecha.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblFecha.setText("Fecha de Creacion");
        jPanel6.add(lblFecha);

        jPanel2.add(jPanel6);

        jLabel1.setText("Fecha Inicio:");
        jPanel1.add(jLabel1);

        lblFI.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblFI.setText("00/00/0000");
        jPanel1.add(lblFI);

        jLabel9.setText("Fecha Final:");
        jPanel1.add(jLabel9);

        lblFF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblFF.setText("00/00/0000");
        jPanel1.add(lblFF);

        jPanel2.add(jPanel1);

        jLabel7.setText("Pedido por:");
        jPanel4.add(jLabel7);

        lblPedido.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblPedido.setText("Pedido");
        jPanel4.add(lblPedido);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel13.setText("Descripción:");
        jPanel7.add(jLabel13);

        jPanel5.add(jPanel7);

        txtDes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel5.add(txtDes);

        getContentPane().add(jPanel5);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        btnReq.setText("Rquerimientos");
        btnReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqActionPerformed(evt);
            }
        });
        jPanel8.add(btnReq);

        btnBack.setText("Regresar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel8.add(btnBack);

        getContentPane().add(jPanel8);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.hide();
        padre.ver.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqActionPerformed
        // TODO add your handling code here:
        padre.add(req);
        req.actual = this.actual;
        req.session = session;
        try {
            req.actual.getRequerimientos(this.db);
            if(req.actual.requerimientos.size()> 0)
            {
                req.actReq = req.actual.requerimientos.get(0);
            }
            req.printActual();
            req.setVisible(true);
            this.hide();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error requerimientos");
        }
    }//GEN-LAST:event_btnReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblFF;
    private javax.swing.JLabel lblFI;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDes;
    // End of variables declaration//GEN-END:variables
}
